/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * ClientVersionRange
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class ClientVersionRange {
  @SerializedName("minimum")
  private SemanticVersion minimum = null;

  @SerializedName("maximum")
  private SemanticVersion maximum = null;

  public ClientVersionRange minimum(SemanticVersion minimum) {
    this.minimum = minimum;
    return this;
  }

   /**
   * Get minimum
   * @return minimum
  **/
  @ApiModelProperty(value = "")
  public SemanticVersion getMinimum() {
    return minimum;
  }

  public void setMinimum(SemanticVersion minimum) {
    this.minimum = minimum;
  }

  public ClientVersionRange maximum(SemanticVersion maximum) {
    this.maximum = maximum;
    return this;
  }

   /**
   * Get maximum
   * @return maximum
  **/
  @ApiModelProperty(value = "")
  public SemanticVersion getMaximum() {
    return maximum;
  }

  public void setMaximum(SemanticVersion maximum) {
    this.maximum = maximum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientVersionRange clientVersionRange = (ClientVersionRange) o;
    return Objects.equals(this.minimum, clientVersionRange.minimum) &&
        Objects.equals(this.maximum, clientVersionRange.maximum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minimum, maximum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientVersionRange {\n");
    
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

