/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * ContinuousStatusCheckNode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class ContinuousStatusCheckNode extends GraphNode {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("thirdPartyPresets")
  private String thirdPartyPresets = null;

  @SerializedName("endpointConfiguration")
  private EndpointConfiguration endpointConfiguration = null;

  @SerializedName("evaluationConfiguration")
  private EvaluationConfiguration evaluationConfiguration = null;

  @SerializedName("statusCheckId")
  private String statusCheckId = null;

  @SerializedName("statusCheckReferenceId")
  private String statusCheckReferenceId = null;

  @SerializedName("intervalSeconds")
  private Integer intervalSeconds = null;

  public ContinuousStatusCheckNode name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ContinuousStatusCheckNode description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ContinuousStatusCheckNode thirdPartyPresets(String thirdPartyPresets) {
    this.thirdPartyPresets = thirdPartyPresets;
    return this;
  }

   /**
   * Get thirdPartyPresets
   * @return thirdPartyPresets
  **/
  @ApiModelProperty(value = "")
  public String getThirdPartyPresets() {
    return thirdPartyPresets;
  }

  public void setThirdPartyPresets(String thirdPartyPresets) {
    this.thirdPartyPresets = thirdPartyPresets;
  }

  public ContinuousStatusCheckNode endpointConfiguration(EndpointConfiguration endpointConfiguration) {
    this.endpointConfiguration = endpointConfiguration;
    return this;
  }

   /**
   * Get endpointConfiguration
   * @return endpointConfiguration
  **/
  @ApiModelProperty(value = "")
  public EndpointConfiguration getEndpointConfiguration() {
    return endpointConfiguration;
  }

  public void setEndpointConfiguration(EndpointConfiguration endpointConfiguration) {
    this.endpointConfiguration = endpointConfiguration;
  }

  public ContinuousStatusCheckNode evaluationConfiguration(EvaluationConfiguration evaluationConfiguration) {
    this.evaluationConfiguration = evaluationConfiguration;
    return this;
  }

   /**
   * Get evaluationConfiguration
   * @return evaluationConfiguration
  **/
  @ApiModelProperty(value = "")
  public EvaluationConfiguration getEvaluationConfiguration() {
    return evaluationConfiguration;
  }

  public void setEvaluationConfiguration(EvaluationConfiguration evaluationConfiguration) {
    this.evaluationConfiguration = evaluationConfiguration;
  }

  public ContinuousStatusCheckNode statusCheckId(String statusCheckId) {
    this.statusCheckId = statusCheckId;
    return this;
  }

   /**
   * Get statusCheckId
   * @return statusCheckId
  **/
  @ApiModelProperty(value = "")
  public String getStatusCheckId() {
    return statusCheckId;
  }

  public void setStatusCheckId(String statusCheckId) {
    this.statusCheckId = statusCheckId;
  }

  public ContinuousStatusCheckNode statusCheckReferenceId(String statusCheckReferenceId) {
    this.statusCheckReferenceId = statusCheckReferenceId;
    return this;
  }

   /**
   * Get statusCheckReferenceId
   * @return statusCheckReferenceId
  **/
  @ApiModelProperty(value = "")
  public String getStatusCheckReferenceId() {
    return statusCheckReferenceId;
  }

  public void setStatusCheckReferenceId(String statusCheckReferenceId) {
    this.statusCheckReferenceId = statusCheckReferenceId;
  }

  public ContinuousStatusCheckNode intervalSeconds(Integer intervalSeconds) {
    this.intervalSeconds = intervalSeconds;
    return this;
  }

   /**
   * Get intervalSeconds
   * @return intervalSeconds
  **/
  @ApiModelProperty(value = "")
  public Integer getIntervalSeconds() {
    return intervalSeconds;
  }

  public void setIntervalSeconds(Integer intervalSeconds) {
    this.intervalSeconds = intervalSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContinuousStatusCheckNode continuousStatusCheckNode = (ContinuousStatusCheckNode) o;
    return Objects.equals(this.name, continuousStatusCheckNode.name) &&
        Objects.equals(this.description, continuousStatusCheckNode.description) &&
        Objects.equals(this.thirdPartyPresets, continuousStatusCheckNode.thirdPartyPresets) &&
        Objects.equals(this.endpointConfiguration, continuousStatusCheckNode.endpointConfiguration) &&
        Objects.equals(this.evaluationConfiguration, continuousStatusCheckNode.evaluationConfiguration) &&
        Objects.equals(this.statusCheckId, continuousStatusCheckNode.statusCheckId) &&
        Objects.equals(this.statusCheckReferenceId, continuousStatusCheckNode.statusCheckReferenceId) &&
        Objects.equals(this.intervalSeconds, continuousStatusCheckNode.intervalSeconds) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, thirdPartyPresets, endpointConfiguration, evaluationConfiguration, statusCheckId, statusCheckReferenceId, intervalSeconds, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContinuousStatusCheckNode {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    thirdPartyPresets: ").append(toIndentedString(thirdPartyPresets)).append("\n");
    sb.append("    endpointConfiguration: ").append(toIndentedString(endpointConfiguration)).append("\n");
    sb.append("    evaluationConfiguration: ").append(toIndentedString(evaluationConfiguration)).append("\n");
    sb.append("    statusCheckId: ").append(toIndentedString(statusCheckId)).append("\n");
    sb.append("    statusCheckReferenceId: ").append(toIndentedString(statusCheckReferenceId)).append("\n");
    sb.append("    intervalSeconds: ").append(toIndentedString(intervalSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

