/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * InfraCommandArgs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class InfraCommandArgs {
  @SerializedName("length")
  private Integer length = null;

  @SerializedName("commandArgs")
  private Map<String, String> unknownArgs = null;

  @SerializedName("cli_args")
  private List<String> cliArgs = null;

  public InfraCommandArgs length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @ApiModelProperty(value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public InfraCommandArgs unknownArgs(Map<String, String> unknownArgs) {
    this.unknownArgs = unknownArgs;
    return this;
  }

  public InfraCommandArgs putUnknownArgsItem(String key, String unknownArgsItem) {
    if (this.unknownArgs == null) {
      this.unknownArgs = new HashMap<String, String>();
    }
    this.unknownArgs.put(key, unknownArgsItem);
    return this;
  }

   /**
   * Get unknownArgs
   * @return unknownArgs
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getUnknownArgs() {
    return unknownArgs;
  }

  public void setUnknownArgs(Map<String, String> unknownArgs) {
    this.unknownArgs = unknownArgs;
  }

  public InfraCommandArgs cliArgs(List<String> cliArgs) {
    this.cliArgs = cliArgs;
    return this;
  }

  public InfraCommandArgs addCliArgsItem(String cliArgsItem) {
    if (this.cliArgs == null) {
      this.cliArgs = new ArrayList<String>();
    }
    this.cliArgs.add(cliArgsItem);
    return this;
  }

   /**
   * Get cliArgs
   * @return cliArgs
  **/
  @ApiModelProperty(value = "")
  public List<String> getCliArgs() {
    return cliArgs;
  }

  public void setCliArgs(List<String> cliArgs) {
    this.cliArgs = cliArgs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfraCommandArgs infraCommandArgs = (InfraCommandArgs) o;
    return Objects.equals(this.length, infraCommandArgs.length) &&
        Objects.equals(this.unknownArgs, infraCommandArgs.unknownArgs) &&
        Objects.equals(this.cliArgs, infraCommandArgs.cliArgs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(length, unknownArgs, cliArgs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfraCommandArgs {\n");
    
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    unknownArgs: ").append(toIndentedString(unknownArgs)).append("\n");
    sb.append("    cliArgs: ").append(toIndentedString(cliArgs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

