/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * Org
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class Org {
  @SerializedName("state")
  private String state = null;

  @SerializedName("clientVersions")
  private Map<String, ClientVersionRange> clientVersions = null;

  @SerializedName("secretSetAt")
  private OffsetDateTime secretSetAt = null;

  @SerializedName("secretSetBy")
  private String secretSetBy = null;

  @SerializedName("identifier")
  private String identifier = null;

  @SerializedName("updatedAt")
  private OffsetDateTime updatedAt = null;

  @SerializedName("certificateSetAt")
  private OffsetDateTime certificateSetAt = null;

  @SerializedName("certificateSetBy")
  private String certificateSetBy = null;

  @SerializedName("certificateCredentials")
  private CertificateAndPrivateKey certificateCredentials = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("attributes")
  private Map<String, Object> attributes = null;

  @SerializedName("oldCertificateSetAt")
  private OffsetDateTime oldCertificateSetAt = null;

  @SerializedName("oldCertificateSetBy")
  private String oldCertificateSetBy = null;

  @SerializedName("oldCertificateAndPrivateKey")
  private CertificateAndPrivateKey oldCertificateAndPrivateKey = null;

  @SerializedName("lastSignatureTimestamp")
  private OffsetDateTime lastSignatureTimestamp = null;

  @SerializedName("certificateAndPrivateKey")
  private CertificateAndPrivateKey certificateAndPrivateKey = null;

  public Org state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public Org clientVersions(Map<String, ClientVersionRange> clientVersions) {
    this.clientVersions = clientVersions;
    return this;
  }

  public Org putClientVersionsItem(String key, ClientVersionRange clientVersionsItem) {
    if (this.clientVersions == null) {
      this.clientVersions = new HashMap<String, ClientVersionRange>();
    }
    this.clientVersions.put(key, clientVersionsItem);
    return this;
  }

   /**
   * Get clientVersions
   * @return clientVersions
  **/
  @ApiModelProperty(value = "")
  public Map<String, ClientVersionRange> getClientVersions() {
    return clientVersions;
  }

  public void setClientVersions(Map<String, ClientVersionRange> clientVersions) {
    this.clientVersions = clientVersions;
  }

  public Org secretSetAt(OffsetDateTime secretSetAt) {
    this.secretSetAt = secretSetAt;
    return this;
  }

   /**
   * Get secretSetAt
   * @return secretSetAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getSecretSetAt() {
    return secretSetAt;
  }

  public void setSecretSetAt(OffsetDateTime secretSetAt) {
    this.secretSetAt = secretSetAt;
  }

  public Org secretSetBy(String secretSetBy) {
    this.secretSetBy = secretSetBy;
    return this;
  }

   /**
   * Get secretSetBy
   * @return secretSetBy
  **/
  @ApiModelProperty(value = "")
  public String getSecretSetBy() {
    return secretSetBy;
  }

  public void setSecretSetBy(String secretSetBy) {
    this.secretSetBy = secretSetBy;
  }

  public Org identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @ApiModelProperty(value = "")
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public Org updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Org certificateSetAt(OffsetDateTime certificateSetAt) {
    this.certificateSetAt = certificateSetAt;
    return this;
  }

   /**
   * Get certificateSetAt
   * @return certificateSetAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCertificateSetAt() {
    return certificateSetAt;
  }

  public void setCertificateSetAt(OffsetDateTime certificateSetAt) {
    this.certificateSetAt = certificateSetAt;
  }

  public Org certificateSetBy(String certificateSetBy) {
    this.certificateSetBy = certificateSetBy;
    return this;
  }

   /**
   * Get certificateSetBy
   * @return certificateSetBy
  **/
  @ApiModelProperty(value = "")
  public String getCertificateSetBy() {
    return certificateSetBy;
  }

  public void setCertificateSetBy(String certificateSetBy) {
    this.certificateSetBy = certificateSetBy;
  }

  public Org certificateCredentials(CertificateAndPrivateKey certificateCredentials) {
    this.certificateCredentials = certificateCredentials;
    return this;
  }

   /**
   * Get certificateCredentials
   * @return certificateCredentials
  **/
  @ApiModelProperty(value = "")
  public CertificateAndPrivateKey getCertificateCredentials() {
    return certificateCredentials;
  }

  public void setCertificateCredentials(CertificateAndPrivateKey certificateCredentials) {
    this.certificateCredentials = certificateCredentials;
  }

  public Org createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Org name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Org attributes(Map<String, Object> attributes) {
    this.attributes = attributes;
    return this;
  }

  public Org putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<String, Object>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, Object> attributes) {
    this.attributes = attributes;
  }

  public Org oldCertificateSetAt(OffsetDateTime oldCertificateSetAt) {
    this.oldCertificateSetAt = oldCertificateSetAt;
    return this;
  }

   /**
   * Get oldCertificateSetAt
   * @return oldCertificateSetAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getOldCertificateSetAt() {
    return oldCertificateSetAt;
  }

  public void setOldCertificateSetAt(OffsetDateTime oldCertificateSetAt) {
    this.oldCertificateSetAt = oldCertificateSetAt;
  }

  public Org oldCertificateSetBy(String oldCertificateSetBy) {
    this.oldCertificateSetBy = oldCertificateSetBy;
    return this;
  }

   /**
   * Get oldCertificateSetBy
   * @return oldCertificateSetBy
  **/
  @ApiModelProperty(value = "")
  public String getOldCertificateSetBy() {
    return oldCertificateSetBy;
  }

  public void setOldCertificateSetBy(String oldCertificateSetBy) {
    this.oldCertificateSetBy = oldCertificateSetBy;
  }

  public Org oldCertificateAndPrivateKey(CertificateAndPrivateKey oldCertificateAndPrivateKey) {
    this.oldCertificateAndPrivateKey = oldCertificateAndPrivateKey;
    return this;
  }

   /**
   * Get oldCertificateAndPrivateKey
   * @return oldCertificateAndPrivateKey
  **/
  @ApiModelProperty(value = "")
  public CertificateAndPrivateKey getOldCertificateAndPrivateKey() {
    return oldCertificateAndPrivateKey;
  }

  public void setOldCertificateAndPrivateKey(CertificateAndPrivateKey oldCertificateAndPrivateKey) {
    this.oldCertificateAndPrivateKey = oldCertificateAndPrivateKey;
  }

  public Org lastSignatureTimestamp(OffsetDateTime lastSignatureTimestamp) {
    this.lastSignatureTimestamp = lastSignatureTimestamp;
    return this;
  }

   /**
   * Get lastSignatureTimestamp
   * @return lastSignatureTimestamp
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastSignatureTimestamp() {
    return lastSignatureTimestamp;
  }

  public void setLastSignatureTimestamp(OffsetDateTime lastSignatureTimestamp) {
    this.lastSignatureTimestamp = lastSignatureTimestamp;
  }

  public Org certificateAndPrivateKey(CertificateAndPrivateKey certificateAndPrivateKey) {
    this.certificateAndPrivateKey = certificateAndPrivateKey;
    return this;
  }

   /**
   * Get certificateAndPrivateKey
   * @return certificateAndPrivateKey
  **/
  @ApiModelProperty(value = "")
  public CertificateAndPrivateKey getCertificateAndPrivateKey() {
    return certificateAndPrivateKey;
  }

  public void setCertificateAndPrivateKey(CertificateAndPrivateKey certificateAndPrivateKey) {
    this.certificateAndPrivateKey = certificateAndPrivateKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Org org = (Org) o;
    return Objects.equals(this.state, org.state) &&
        Objects.equals(this.clientVersions, org.clientVersions) &&
        Objects.equals(this.secretSetAt, org.secretSetAt) &&
        Objects.equals(this.secretSetBy, org.secretSetBy) &&
        Objects.equals(this.identifier, org.identifier) &&
        Objects.equals(this.updatedAt, org.updatedAt) &&
        Objects.equals(this.certificateSetAt, org.certificateSetAt) &&
        Objects.equals(this.certificateSetBy, org.certificateSetBy) &&
        Objects.equals(this.certificateCredentials, org.certificateCredentials) &&
        Objects.equals(this.createdAt, org.createdAt) &&
        Objects.equals(this.name, org.name) &&
        Objects.equals(this.attributes, org.attributes) &&
        Objects.equals(this.oldCertificateSetAt, org.oldCertificateSetAt) &&
        Objects.equals(this.oldCertificateSetBy, org.oldCertificateSetBy) &&
        Objects.equals(this.oldCertificateAndPrivateKey, org.oldCertificateAndPrivateKey) &&
        Objects.equals(this.lastSignatureTimestamp, org.lastSignatureTimestamp) &&
        Objects.equals(this.certificateAndPrivateKey, org.certificateAndPrivateKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(state, clientVersions, secretSetAt, secretSetBy, identifier, updatedAt, certificateSetAt, certificateSetBy, certificateCredentials, createdAt, name, attributes, oldCertificateSetAt, oldCertificateSetBy, oldCertificateAndPrivateKey, lastSignatureTimestamp, certificateAndPrivateKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Org {\n");
    
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    clientVersions: ").append(toIndentedString(clientVersions)).append("\n");
    sb.append("    secretSetAt: ").append(toIndentedString(secretSetAt)).append("\n");
    sb.append("    secretSetBy: ").append(toIndentedString(secretSetBy)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    certificateSetAt: ").append(toIndentedString(certificateSetAt)).append("\n");
    sb.append("    certificateSetBy: ").append(toIndentedString(certificateSetBy)).append("\n");
    sb.append("    certificateCredentials: ").append(toIndentedString(certificateCredentials)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    oldCertificateSetAt: ").append(toIndentedString(oldCertificateSetAt)).append("\n");
    sb.append("    oldCertificateSetBy: ").append(toIndentedString(oldCertificateSetBy)).append("\n");
    sb.append("    oldCertificateAndPrivateKey: ").append(toIndentedString(oldCertificateAndPrivateKey)).append("\n");
    sb.append("    lastSignatureTimestamp: ").append(toIndentedString(lastSignatureTimestamp)).append("\n");
    sb.append("    certificateAndPrivateKey: ").append(toIndentedString(certificateAndPrivateKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

