/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * OutstandingRequests
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class OutstandingRequests {
  @SerializedName("assetToRequestMap")
  private Map<String, List<SharedAsset>> assetToRequestMap = null;

  @SerializedName("idToTeamMapping")
  private Map<String, SharedTeam> idToTeamMapping = null;

  public OutstandingRequests assetToRequestMap(Map<String, List<SharedAsset>> assetToRequestMap) {
    this.assetToRequestMap = assetToRequestMap;
    return this;
  }

  public OutstandingRequests putAssetToRequestMapItem(String key, List<SharedAsset> assetToRequestMapItem) {
    if (this.assetToRequestMap == null) {
      this.assetToRequestMap = new HashMap<String, List<SharedAsset>>();
    }
    this.assetToRequestMap.put(key, assetToRequestMapItem);
    return this;
  }

   /**
   * Get assetToRequestMap
   * @return assetToRequestMap
  **/
  @ApiModelProperty(value = "")
  public Map<String, List<SharedAsset>> getAssetToRequestMap() {
    return assetToRequestMap;
  }

  public void setAssetToRequestMap(Map<String, List<SharedAsset>> assetToRequestMap) {
    this.assetToRequestMap = assetToRequestMap;
  }

  public OutstandingRequests idToTeamMapping(Map<String, SharedTeam> idToTeamMapping) {
    this.idToTeamMapping = idToTeamMapping;
    return this;
  }

  public OutstandingRequests putIdToTeamMappingItem(String key, SharedTeam idToTeamMappingItem) {
    if (this.idToTeamMapping == null) {
      this.idToTeamMapping = new HashMap<String, SharedTeam>();
    }
    this.idToTeamMapping.put(key, idToTeamMappingItem);
    return this;
  }

   /**
   * Get idToTeamMapping
   * @return idToTeamMapping
  **/
  @ApiModelProperty(value = "")
  public Map<String, SharedTeam> getIdToTeamMapping() {
    return idToTeamMapping;
  }

  public void setIdToTeamMapping(Map<String, SharedTeam> idToTeamMapping) {
    this.idToTeamMapping = idToTeamMapping;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutstandingRequests outstandingRequests = (OutstandingRequests) o;
    return Objects.equals(this.assetToRequestMap, outstandingRequests.assetToRequestMap) &&
        Objects.equals(this.idToTeamMapping, outstandingRequests.idToTeamMapping);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetToRequestMap, idToTeamMapping);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutstandingRequests {\n");
    
    sb.append("    assetToRequestMap: ").append(toIndentedString(assetToRequestMap)).append("\n");
    sb.append("    idToTeamMapping: ").append(toIndentedString(idToTeamMapping)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

