/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * RecommendedScenarioResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class RecommendedScenarioResponse {
  @SerializedName("guid")
  private String guid = null;

  @SerializedName("priority")
  private Integer priority = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("hypothesis")
  private String hypothesis = null;

  @SerializedName("steps")
  private List<Map<String, Object>> steps = null;

  @SerializedName("graph")
  private ScenarioGraph graph = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  /**
   * Gets or Sets tiers
   */
  @JsonAdapter(TiersEnum.Adapter.class)
  public enum TiersEnum {
    ENTERPRISE("Enterprise"),
    
    FREE("Free");

    private String value;

    TiersEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TiersEnum fromValue(String text) {
      for (TiersEnum b : TiersEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TiersEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TiersEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TiersEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TiersEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("tiers")
  private List<TiersEnum> tiers = null;

  @SerializedName("staticEndpointName")
  private String staticEndpointName = null;

  @SerializedName("multiSelectTags")
  private Map<String, List<String>> multiSelectTags = null;

  public RecommendedScenarioResponse guid(String guid) {
    this.guid = guid;
    return this;
  }

   /**
   * Get guid
   * @return guid
  **/
  @ApiModelProperty(value = "")
  public String getGuid() {
    return guid;
  }

  public void setGuid(String guid) {
    this.guid = guid;
  }

  public RecommendedScenarioResponse priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public RecommendedScenarioResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RecommendedScenarioResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RecommendedScenarioResponse hypothesis(String hypothesis) {
    this.hypothesis = hypothesis;
    return this;
  }

   /**
   * Get hypothesis
   * @return hypothesis
  **/
  @ApiModelProperty(value = "")
  public String getHypothesis() {
    return hypothesis;
  }

  public void setHypothesis(String hypothesis) {
    this.hypothesis = hypothesis;
  }

  public RecommendedScenarioResponse steps(List<Map<String, Object>> steps) {
    this.steps = steps;
    return this;
  }

  public RecommendedScenarioResponse addStepsItem(Map<String, Object> stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<Map<String, Object>>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @ApiModelProperty(value = "")
  public List<Map<String, Object>> getSteps() {
    return steps;
  }

  public void setSteps(List<Map<String, Object>> steps) {
    this.steps = steps;
  }

  public RecommendedScenarioResponse graph(ScenarioGraph graph) {
    this.graph = graph;
    return this;
  }

   /**
   * Get graph
   * @return graph
  **/
  @ApiModelProperty(value = "")
  public ScenarioGraph getGraph() {
    return graph;
  }

  public void setGraph(ScenarioGraph graph) {
    this.graph = graph;
  }

  public RecommendedScenarioResponse createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public RecommendedScenarioResponse updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public RecommendedScenarioResponse tiers(List<TiersEnum> tiers) {
    this.tiers = tiers;
    return this;
  }

  public RecommendedScenarioResponse addTiersItem(TiersEnum tiersItem) {
    if (this.tiers == null) {
      this.tiers = new ArrayList<TiersEnum>();
    }
    this.tiers.add(tiersItem);
    return this;
  }

   /**
   * Get tiers
   * @return tiers
  **/
  @ApiModelProperty(value = "")
  public List<TiersEnum> getTiers() {
    return tiers;
  }

  public void setTiers(List<TiersEnum> tiers) {
    this.tiers = tiers;
  }

  public RecommendedScenarioResponse staticEndpointName(String staticEndpointName) {
    this.staticEndpointName = staticEndpointName;
    return this;
  }

   /**
   * Get staticEndpointName
   * @return staticEndpointName
  **/
  @ApiModelProperty(value = "")
  public String getStaticEndpointName() {
    return staticEndpointName;
  }

  public void setStaticEndpointName(String staticEndpointName) {
    this.staticEndpointName = staticEndpointName;
  }

  public RecommendedScenarioResponse multiSelectTags(Map<String, List<String>> multiSelectTags) {
    this.multiSelectTags = multiSelectTags;
    return this;
  }

  public RecommendedScenarioResponse putMultiSelectTagsItem(String key, List<String> multiSelectTagsItem) {
    if (this.multiSelectTags == null) {
      this.multiSelectTags = new HashMap<String, List<String>>();
    }
    this.multiSelectTags.put(key, multiSelectTagsItem);
    return this;
  }

   /**
   * Get multiSelectTags
   * @return multiSelectTags
  **/
  @ApiModelProperty(value = "")
  public Map<String, List<String>> getMultiSelectTags() {
    return multiSelectTags;
  }

  public void setMultiSelectTags(Map<String, List<String>> multiSelectTags) {
    this.multiSelectTags = multiSelectTags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendedScenarioResponse recommendedScenarioResponse = (RecommendedScenarioResponse) o;
    return Objects.equals(this.guid, recommendedScenarioResponse.guid) &&
        Objects.equals(this.priority, recommendedScenarioResponse.priority) &&
        Objects.equals(this.name, recommendedScenarioResponse.name) &&
        Objects.equals(this.description, recommendedScenarioResponse.description) &&
        Objects.equals(this.hypothesis, recommendedScenarioResponse.hypothesis) &&
        Objects.equals(this.steps, recommendedScenarioResponse.steps) &&
        Objects.equals(this.graph, recommendedScenarioResponse.graph) &&
        Objects.equals(this.createdAt, recommendedScenarioResponse.createdAt) &&
        Objects.equals(this.updatedAt, recommendedScenarioResponse.updatedAt) &&
        Objects.equals(this.tiers, recommendedScenarioResponse.tiers) &&
        Objects.equals(this.staticEndpointName, recommendedScenarioResponse.staticEndpointName) &&
        Objects.equals(this.multiSelectTags, recommendedScenarioResponse.multiSelectTags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guid, priority, name, description, hypothesis, steps, graph, createdAt, updatedAt, tiers, staticEndpointName, multiSelectTags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendedScenarioResponse {\n");
    
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hypothesis: ").append(toIndentedString(hypothesis)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    graph: ").append(toIndentedString(graph)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    tiers: ").append(toIndentedString(tiers)).append("\n");
    sb.append("    staticEndpointName: ").append(toIndentedString(staticEndpointName)).append("\n");
    sb.append("    multiSelectTags: ").append(toIndentedString(multiSelectTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

