/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;

/**
 * ScenarioScheduleInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class ScenarioScheduleInput {
  @SerializedName("trigger")
  private Map<String, Object> trigger = null;

  @SerializedName("scenarioId")
  private String scenarioId = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  public ScenarioScheduleInput trigger(Map<String, Object> trigger) {
    this.trigger = trigger;
    return this;
  }

  public ScenarioScheduleInput putTriggerItem(String key, Object triggerItem) {
    if (this.trigger == null) {
      this.trigger = new HashMap<String, Object>();
    }
    this.trigger.put(key, triggerItem);
    return this;
  }

   /**
   * Get trigger
   * @return trigger
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getTrigger() {
    return trigger;
  }

  public void setTrigger(Map<String, Object> trigger) {
    this.trigger = trigger;
  }

  public ScenarioScheduleInput scenarioId(String scenarioId) {
    this.scenarioId = scenarioId;
    return this;
  }

   /**
   * Get scenarioId
   * @return scenarioId
  **/
  @ApiModelProperty(value = "")
  public String getScenarioId() {
    return scenarioId;
  }

  public void setScenarioId(String scenarioId) {
    this.scenarioId = scenarioId;
  }

  public ScenarioScheduleInput enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScenarioScheduleInput scenarioScheduleInput = (ScenarioScheduleInput) o;
    return Objects.equals(this.trigger, scenarioScheduleInput.trigger) &&
        Objects.equals(this.scenarioId, scenarioScheduleInput.scenarioId) &&
        Objects.equals(this.enabled, scenarioScheduleInput.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trigger, scenarioId, enabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScenarioScheduleInput {\n");
    
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("    scenarioId: ").append(toIndentedString(scenarioId)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

