/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;

/**
 * ScenarioGraph
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class ScenarioGraph {
  @SerializedName("nodes")
  private Map<String, GraphNode> nodes = null;

  @SerializedName("startId")
  private String startId = null;

  public ScenarioGraph nodes(Map<String, GraphNode> nodes) {
    this.nodes = nodes;
    return this;
  }

  public ScenarioGraph putNodesItem(String key, GraphNode nodesItem) {
    if (this.nodes == null) {
      this.nodes = new HashMap<String, GraphNode>();
    }
    this.nodes.put(key, nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  @ApiModelProperty(value = "")
  public Map<String, GraphNode> getNodes() {
    return nodes;
  }

  public void setNodes(Map<String, GraphNode> nodes) {
    this.nodes = nodes;
  }

  public ScenarioGraph startId(String startId) {
    this.startId = startId;
    return this;
  }

   /**
   * Get startId
   * @return startId
  **/
  @ApiModelProperty(value = "")
  public String getStartId() {
    return startId;
  }

  public void setStartId(String startId) {
    this.startId = startId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScenarioGraph scenarioGraph = (ScenarioGraph) o;
    return Objects.equals(this.nodes, scenarioGraph.nodes) &&
        Objects.equals(this.startId, scenarioGraph.startId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nodes, startId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScenarioGraph {\n");
    
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    startId: ").append(toIndentedString(startId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

