/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * TeamUsageReport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class TeamUsageReport {
  @SerializedName("companyId")
  private String companyId = null;

  @SerializedName("teamId")
  private String teamId = null;

  @SerializedName("teamName")
  private String teamName = null;

  @SerializedName("startDate")
  private String startDate = null;

  @SerializedName("endDate")
  private String endDate = null;

  @SerializedName("gremlinMetrics")
  private GremlinMetrics gremlinMetrics = null;

  public TeamUsageReport companyId(String companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  @ApiModelProperty(value = "")
  public String getCompanyId() {
    return companyId;
  }

  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }

  public TeamUsageReport teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @ApiModelProperty(value = "")
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public TeamUsageReport teamName(String teamName) {
    this.teamName = teamName;
    return this;
  }

   /**
   * Get teamName
   * @return teamName
  **/
  @ApiModelProperty(value = "")
  public String getTeamName() {
    return teamName;
  }

  public void setTeamName(String teamName) {
    this.teamName = teamName;
  }

  public TeamUsageReport startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public TeamUsageReport endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @ApiModelProperty(value = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public TeamUsageReport gremlinMetrics(GremlinMetrics gremlinMetrics) {
    this.gremlinMetrics = gremlinMetrics;
    return this;
  }

   /**
   * Get gremlinMetrics
   * @return gremlinMetrics
  **/
  @ApiModelProperty(value = "")
  public GremlinMetrics getGremlinMetrics() {
    return gremlinMetrics;
  }

  public void setGremlinMetrics(GremlinMetrics gremlinMetrics) {
    this.gremlinMetrics = gremlinMetrics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamUsageReport teamUsageReport = (TeamUsageReport) o;
    return Objects.equals(this.companyId, teamUsageReport.companyId) &&
        Objects.equals(this.teamId, teamUsageReport.teamId) &&
        Objects.equals(this.teamName, teamUsageReport.teamName) &&
        Objects.equals(this.startDate, teamUsageReport.startDate) &&
        Objects.equals(this.endDate, teamUsageReport.endDate) &&
        Objects.equals(this.gremlinMetrics, teamUsageReport.gremlinMetrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyId, teamId, teamName, startDate, endDate, gremlinMetrics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamUsageReport {\n");
    
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    teamName: ").append(toIndentedString(teamName)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    gremlinMetrics: ").append(toIndentedString(gremlinMetrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

