/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * TestEvaluationConfigurationResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-22T16:18:53.536Z")



public class TestEvaluationConfigurationResponse {
  @SerializedName("testEndpointResponse")
  private EndpointResponse testEndpointResponse = null;

  @SerializedName("testEvaluationResults")
  private EvaluationResults testEvaluationResults = null;

  public TestEvaluationConfigurationResponse testEndpointResponse(EndpointResponse testEndpointResponse) {
    this.testEndpointResponse = testEndpointResponse;
    return this;
  }

   /**
   * Get testEndpointResponse
   * @return testEndpointResponse
  **/
  @ApiModelProperty(value = "")
  public EndpointResponse getTestEndpointResponse() {
    return testEndpointResponse;
  }

  public void setTestEndpointResponse(EndpointResponse testEndpointResponse) {
    this.testEndpointResponse = testEndpointResponse;
  }

  public TestEvaluationConfigurationResponse testEvaluationResults(EvaluationResults testEvaluationResults) {
    this.testEvaluationResults = testEvaluationResults;
    return this;
  }

   /**
   * Get testEvaluationResults
   * @return testEvaluationResults
  **/
  @ApiModelProperty(value = "")
  public EvaluationResults getTestEvaluationResults() {
    return testEvaluationResults;
  }

  public void setTestEvaluationResults(EvaluationResults testEvaluationResults) {
    this.testEvaluationResults = testEvaluationResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestEvaluationConfigurationResponse testEvaluationConfigurationResponse = (TestEvaluationConfigurationResponse) o;
    return Objects.equals(this.testEndpointResponse, testEvaluationConfigurationResponse.testEndpointResponse) &&
        Objects.equals(this.testEvaluationResults, testEvaluationConfigurationResponse.testEvaluationResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testEndpointResponse, testEvaluationResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestEvaluationConfigurationResponse {\n");
    
    sb.append("    testEndpointResponse: ").append(toIndentedString(testEndpointResponse)).append("\n");
    sb.append("    testEvaluationResults: ").append(toIndentedString(testEvaluationResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

