/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.api;

import com.gremlin.api.ApiGremlinException;
import com.gremlin.api.model.HaltRequest;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for HaltsApi
 */
@Ignore
public class HaltsApiTest {

    private final HaltsApi api = new HaltsApi();

    
    /**
     * Idempotently halt all active impacts across the Gremlin platform
     *
     * # Authorization Schema ## [__Bearer Tokens__](https://www.gremlin.com/docs/api-reference/examples/#authentication-and-access-tokens) ### Role Based Access Control [&#x60;TEAM_DEFAULT&#x60;](https://www.gremlin.com/docs/user-management/access-control/#privileges) 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void haltAllTest() throws ApiGremlinException {
        Object teamId = null;
        HaltRequest body = null;
        api.haltAll(teamId, body);

        // TODO: test validations
    }
    
}
