/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.api;

import com.gremlin.api.ApiGremlinException;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for UsersAuthApi
 */
@Ignore
public class UsersAuthApiTest {

    private final UsersAuthApi api = new UsersAuthApi();

    
    /**
     * Authenticate a user.
     *
     * 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void auth1Test() throws ApiGremlinException {
        String email = null;
        String password = null;
        String companyName = null;
        Boolean getCompanySession = null;
        api.auth1(email, password, companyName, getCompanySession);

        // TODO: test validations
    }
    
    /**
     * Email active company affiliations.
     *
     * 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void companyAffiliationsEmailTest() throws ApiGremlinException {
        String email = null;
        api.companyAffiliationsEmail(email);

        // TODO: test validations
    }
    
    /**
     * Invalidates a user&#39;s current session, if it exists.
     *
     * # Authorization Schema ## [__Bearer Tokens__](https://www.gremlin.com/docs/api-reference/examples/#authentication-and-access-tokens) ### Role Based Access Control [&#x60;COMPANY_DEFAULT&#x60;](https://www.gremlin.com/docs/user-management/access-control/#privileges) 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void invalidateTest() throws ApiGremlinException {
        api.invalidate();

        // TODO: test validations
    }
    
    /**
     * Gets SAML Service Provider metadata.
     *
     * 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void samlMetadataTest() throws ApiGremlinException {
        String companyName = null;
        api.samlMetadata(companyName);

        // TODO: test validations
    }
    
}
