/*
 * The Gremlin API
 * The API for interacting with Gremlin's 'Failure as a Service'
 *
 * OpenAPI spec version: v1
 * Contact: support@gremlin.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.gremlin.api.api;

import com.gremlin.api.ApiGremlinException;
import com.gremlin.api.model.Webhook;
import com.gremlin.api.model.WebhookRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for WebhooksApi
 */
@Ignore
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    
    /**
     * 
     *
     * # Authorization Schema ## [__Bearer Tokens__](https://www.gremlin.com/docs/api-reference/examples/#authentication-and-access-tokens) ### Role Based Access Control [&#x60;MANAGE_WEBHOOKS&#x60;](https://www.gremlin.com/docs/user-management/access-control/#privileges) 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void createWebhook1Test() throws ApiGremlinException {
        WebhookRequest body = null;
        Object teamId = null;
        api.createWebhook1(body, teamId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * # Authorization Schema ## [__Bearer Tokens__](https://www.gremlin.com/docs/api-reference/examples/#authentication-and-access-tokens) ### Role Based Access Control [&#x60;MANAGE_WEBHOOKS&#x60;](https://www.gremlin.com/docs/user-management/access-control/#privileges) 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void deleteWebhookTest() throws ApiGremlinException {
        String guid = null;
        Object teamId = null;
        api.deleteWebhook(guid, teamId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * # Authorization Schema ## [__Bearer Tokens__](https://www.gremlin.com/docs/api-reference/examples/#authentication-and-access-tokens) ### Role Based Access Control [&#x60;MANAGE_WEBHOOKS&#x60;](https://www.gremlin.com/docs/user-management/access-control/#privileges) 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void getWebhookByIdTest() throws ApiGremlinException {
        String guid = null;
        Object teamId = null;
        Webhook response = api.getWebhookById(guid, teamId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * # Authorization Schema ## [__Bearer Tokens__](https://www.gremlin.com/docs/api-reference/examples/#authentication-and-access-tokens) ### Role Based Access Control [&#x60;MANAGE_WEBHOOKS&#x60;](https://www.gremlin.com/docs/user-management/access-control/#privileges) 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void getWebhooksTest() throws ApiGremlinException {
        String state = null;
        Object teamId = null;
        List<Webhook> response = api.getWebhooks(state, teamId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * # Authorization Schema ## [__Bearer Tokens__](https://www.gremlin.com/docs/api-reference/examples/#authentication-and-access-tokens) ### Role Based Access Control [&#x60;MANAGE_WEBHOOKS&#x60;](https://www.gremlin.com/docs/user-management/access-control/#privileges) 
     *
     * @throws ApiGremlinException
     *          if the Api call fails
     */
    @Test
    public void updateWebhookTest() throws ApiGremlinException {
        String guid = null;
        WebhookRequest body = null;
        Object teamId = null;
        api.updateWebhook(guid, body, teamId);

        // TODO: test validations
    }
    
}
